---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unibee-mysql-config
  labels:
    app: unibee-mysql
data:
  my.cnf: |-
    [client]
    default-character-set=utf8mb4
    [mysql]
    default-character-set=utf8mb4
    [mysqld] 
    lower_case_table_names=1
    default-time_zone='+8:00'
    default_authentication_plugin=mysql_native_password
    max_connections = 2000
    secure_file_priv=/var/lib/mysql
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    gtid_mode = on
    enforce_gtid_consistency = on
    # binlog config limitation
    expire_logs_days = 3
    max_binlog_size = 100m
    binlog_cache_size = 4m
    max_binlog_cache_size = 512m    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unibee-mysql
  labels:
    app: unibee-mysql
spec:
  serviceName: "unibee-mysql"
  replicas: 1
  selector:
    matchLabels:
      app: unibee-mysql
  template:
    metadata:
      labels:
        app: unibee-mysql
    spec:     
      initContainers:
      - name: initsql
        image: busybox   
        volumeMounts:
        - name: unibee-mysql-shared-data
          mountPath: /docker-entrypoint-initdb.d      
        command:
        - /bin/sh
        - -c
        - "cd /docker-entrypoint-initdb.d && wget https://raw.githubusercontent.com/UniB-e-e/unibee_deploy/main/mysql/structure.sql"         
      containers:
      - name: unibee-mysql
        image: mysql:8.0.13
        ports:
        - containerPort: 3306
          name: http
        env:
        - name: MYSQL_ROOT_PASSWORD 
          value: "changeme"
        - name: MYSQL_USER
          value: "unibee"
        - name: MYSQL_PASSWORD 
          value: "changeme"         
        - name: MYSQL_DATABASE 
          value: "unibee"       
        - name: lower_case_table_names
          value: "1"                       
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          exec:
            command: ["mysqladmin", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "ping"]
        readinessProbe:  
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          exec:
            command: ["mysqladmin", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "ping"]
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        # You can uncomment this to make database persistence
        # - name: mysql-data
        #   mountPath: /var/lib/mysql        
        - name: unibee-mysql-shared-data
          mountPath: /docker-entrypoint-initdb.d       
        - name: config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
      volumes:
      - name: unibee-mysql-shared-data
        emptyDir: {}      
      - name: config      
        configMap:
          name: unibee-mysql-config
  # You can uncomment this and change to your storage class name to make database persistence          
  # volumeClaimTemplates:
  # - metadata:
  #     name: mysql-data
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: "${YOUR_STORAGE_CLASS_NAME}"
  #     resources:
  #       requests:
  #         storage: 100Gi          

---
kind: Service
apiVersion: v1
metadata:
  name: unibee-mysql-svc
  namespace: default
  labels:
    app: unibee-mysql-svc
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: http
  selector:
    app: unibee-mysql
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster